use meghana;
CREATE TABLE EMPDETAILS(
ID INT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
SALARY BIGINT
);

INSERT INTO EMPDETAILS VALUES (1,"JOHN",40000),(2,"ALEX",250000),(3,"SIMON",43000);

CREATE TABLE MARITIALSTATUS(
ID INT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
STATUSS VARCHAR(10)
);

INSERT INTO MARITALSTATUS VALUES (1,"JOHN","MARRIED"),(3,"SIMON","MARRIED"),(4,"STELLA","UNMARRIED");

SELECT * FROM EMPDETAILS;
SELECT * FROM MARITALSTATUS;
SELECT EMPDETAILS.ID,EMPDETAILS.NAME,SALARY,STATUSS FROM EMPODETAILS INNER JOIN MARITALSTATUS ON EMPDETAILS.ID


------LEFT JOINT 
SELECT EMPDETAILS.ID,EMPDETAILS.NAME,SALARY,STATUSS FROM EMPDETAILS
LEFT JOINT 
MARITIALSTATUS ON EMPDETAILS.ID = MARITIALSTATUS.ID;

